# Generated by Django 2.0.2 on 2018-02-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qs', models.CharField(max_length=700)),
                ('qsno', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=700)),
                ('option2', models.CharField(max_length=700)),
                ('option3', models.CharField(max_length=700)),
                ('option4', models.CharField(max_length=700)),
            ],
        ),
    ]
